### Retrieve all patients
GET http://localhost:3001/api/patients

### Get one patient
GET http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667

### Get another patient
GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667

### Get patient with no entries
GET http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667

### Add patient
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Ethan Weiner",
  "dateOfBirth": "03-19-2002",
  "ssn": "SSN",
  "gender": "male",
  "occupation": "SWE"
}

### Add invalid patient
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Ethan Weiner",
  "dateOfBirth": "03-19-2002",
  "ssn": "SSN",
  "gender": 55,
  "occupation": "SWE"
}

### Add invalid patient 2
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Ethan Weiner",
  "ssn": "SSN",
  "gender": "male",
  "occupation": "SWE"
}