@hostname = http://localhost
@port = {{$dotenv PORT}}
@host = {{hostname}}:{{port}}

### Get all persons
GET {{host}}/api/persons

### Get one person
GET {{host}}/api/persons/asf2w4362346

### Get invalid person
GET {{host}}/api/persons/abcdef

### Delete one person
DELETE {{host}}/api/persons/6362ffead90cf673f0050f01

### Delete invalid person
DELETE {{host}}/api/persons/6362

### Add a person
POST {{host}}/api/persons
Content-Type: application/json

{
  "name": "E-Wein-Dog",
  "number": "123-123-1234"
}

### Missing number
POST {{host}}/api/persons
Content-Type: application/json

{
  "name": "E-Wein-Dogs"
}

### Missing name
POST {{host}}/api/persons
Content-Type: application/json

{
  "number": "12-123423463"
}

### Taken name
POST {{host}}/api/persons
Content-Type: application/json

{
  "name": "Grace Weiner",
  "number": "123-123-1234"
}

### Wrong content types
POST {{host}}/api/persons
Content-Type: text/plain

{
  "name": "Test Weiner",
  "number": "123-123-1234"
}

### Update number
PUT {{host}}/api/persons/6362c65e57268c1942c0e7a1
Content-Type: application/json

{
  "name": "Lori Weiner",
  "number": "999-999-9999"
}

### Name too short
POST {{host}}/api/persons
Content-Type: application/json

{
  "name": "AC",
  "number": "123-123-1234"
}

### Name too short
PUT {{host}}/api/persons/6362c65e57268c1942c0e7a1
Content-Type: application/json

{
  "name": "AB",
  "number": "123-123-1234"
}

### Valid phone numbers
POST {{host}}/api/persons
Content-Type: application/json

{
  "name": "Valid Phone #1",
  "number": "09-1234556"
}

###
POST {{host}}/api/persons
Content-Type: application/json

{
  "name": "Valid Phone #3",
  "number": "040-22334455"
}

### Invalid phone #s
POST {{host}}/api/persons
Content-Type: application/json

{
  "name": "Invalid Phone #",
  "number": "1234556"
}

###
POST {{host}}/api/persons
Content-Type: application/json

{
  "name": "Invalid Phone #3",
  "number": "1234-22334455"
}